---
- name: Install Nova packages (Ubuntu)
  package:
    name:
      - nova-api
      - nova-scheduler
      - nova-conductor
      - nova-compute
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
